config/routes.rb
Rails.application.routes.draw do

 
  devise_for :users
  root to:'events#index'
  resources :events, only: [:index, :new, :show, :create]
  resources :user, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :user
    belongs_to :event

end

app/models/event.rb
class Event < ApplicationRecord
    has_many :attendances
    belongs_to :user

    validates :start_date, presence: true, if: :is_datetime_passed?
    validates :duration, presence: true, numericality: { only_integer: true, greater_than: 0 }
    validates :title, presence: true, length: { in: 5..140 }
    validates :description, presence: true, length: { in: 20..1000 }
    validates :price, presence: true, numericality: { only_integer: true, greater_than: 0, less_than: 1000 }
    validates :location, presence: true
  
    def is_datetime_passed?
      if start_date < Date.today
        return false
      else
        return true
      end
    end
  
   
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    after_create :welcome_send

    has_many :events
    has_many :attendances

    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :description, presence: true, length: { in: 6..200 }
    validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email valide" }


    def welcome_send
        UserMailer.welcome_email(self).deliver_now
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_devise_parameters, if: :devise_controller?

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :description, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :description, :email, :password, :password_confirmation)}
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
 
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
    @end_date = self.end_date
  end

  def create
    my_date = Time.now + 6.days
    @event = Event.new(
      start_date: my_date,
      duration: params[:duration],
      title: params[:title],
      description: params[:description],
      price: params[:price],
      location: params[:location],
      user_id: current_user.id
    )

    if @event.save # essaie de sauvegarder en base @event
      # si ça marche, il redirige vers la page d'index du site
      puts "Tu as réussi"
      render :show
    else
      # sinon, il render la view new (qui est celle sur laquelle on est déjà)
      puts "ca ne fontionne pas"
      render new_event_path
    end
  end

  def end_date
    event_start = Event.find(params[:id]).start_date
    event_duration = Event.find(params[:id]).duration

    return event_start + (event_duration*60*60)
  end
end

app/controllers/users_controller.rb
class UserController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def Index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">

<h1>Bienvenue, liste des EVENTS</h1>

<div class="row">
  <% @events.each do |event| %>
    <div class="col-sm-4" style="padding: 30px">
      <div class="card">
        <div class="card-header">
          <h4><%= event.title %></h4>
        </div>
        <div class="card-body">
          <p>Description : <%= event.description %></p>
          <p>Location : <%= event.location %></p>
          <p>Price : <%= event.price %></p>
          <%= link_to "Voir", event_path(event.id), class:"btn btn-success" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

</div>
</div>
</div>

app/views/events/new.html.erb
<% if @event.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <p>Erreur</p>
    <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h2>Ajoute ton évenement</h2>

      <%= form_tag url_for(action: 'create'), method: "post" do %>

        <div class="form-group">
          <%= label_tag 'Title' %>
          <%= text_field_tag 'title' %>
        </div>

        <div class="form-group">
          <%= label_tag 'Description' %> <br>
          <%= text_area_tag 'description' %>
        </div>

        <div class="form-group">
          <%= label_tag 'Prix' %>
          <%= text_field_tag 'price' %>
        </div>

        <div class="form-group">
          <%= label_tag 'Lieu' %>
          <%= text_field_tag 'location' %>
        </div>

        <div class="form-group">
          <%= label_tag 'Durée' %>
          <%= text_field_tag 'duration' %>
        </div>

        <%= submit_tag "Validation" %>

      <% end %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">

<div class="card card-gossip">
  <div class="card-header">
    <H2><%= @event.title %></h2>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p>Description : <%= @event.description %></p>
      <p>Location : <%= @event.location %></p>
      <p>Autor : <%= @event.user.email %></p>
      <p>Date de début : <%= @event.start_date %></p>
      <p>Date de fin : <%= @end_date %></p>
      <p>Price : <%= @event.price %></p>
    </blockquote>
  </div>
</div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">



    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

<header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
       

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
         
          <ul class="nav navbar-nav navbar-right">

        <%= link_to "Home", root_path, class: 'navbar-brand' %>

            

            <% if user_signed_in? %>
              <li><%= link_to "Ajout un Event", new_event_path, class: 'navbar-brand' %></li>
                <% else %>
                    <li><%= link_to "Ajout un Event", new_user_session_path, class: 'navbar-brand' %></li>
            <% end %>


            <% if current_user %>
              <li><%= link_to 'Ton compte',edit_user_registration_path %></li>
              <li><%= link_to 'Deconnexion', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "S'inscrire", new_user_registration_path, class: 'nav-link' %></li>
              <li><%= link_to "Se connecter", new_user_session_path, class: 'nav-link' %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>


    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h2>EVENTBRITE</h2>
<p>
  The time is now: <%= Time.now %>
</p>